FROM node:current-alpine3.22 AS test
WORKDIR /app

RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY src ./src
COPY __tests__ ./__tests__
COPY vitest.config.mts ./vitest.config.mts

RUN pnpm install

CMD ["pnpm", "test"]
