services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - eduairet-website:/app
    environment:
      - CI=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    command: sh -c "pnpm dev"

volumes:
  eduairet-website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
