name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: >
          --dns 8.8.8.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        run: |
          docker build -t eduairet-website-test .
      - name: Run tests in Docker
        run: |
          docker run --rm eduairet-website-test pnpm test
